# Generated by Django 4.2.2 on 2023-06-26 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parkings',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date_time', models.DateTimeField()),
                ('reservation_hours', models.PositiveSmallIntegerField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_reservation', related_query_name='parking_reservation', to='parking.parking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservation', related_query_name='user_reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
