# Generated by Django 4.2.2 on 2023-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
